---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello
  namespace: lamanifest
  labels:
    app: hello

spec:

  selector:
    matchLabels:
       app: hello

  templates:
    metadata:
      labels:
        app: hello

    spec:
      containers:
      - name: hello
        image: linuxacademycontent/gitops:hellov1.0
